parsing device out of context agent
dbt-labs/segment pull request #3
Opened 2018-11-14 15:07 UTC by eogilvy12

### Device 

* The device can be parsed from the `context_user_agent` field.
* I think this still needs some alterations to make sure it covers as much as we want it to but this field is frequently requested for segmentation. I think there is benefit to having both a granular and categorized field but happy to discuss!

2018-11-15 14:08 UTC, jthandy commented
@eogilvy12 I'm good to go on the overall business logic and agree that there are two useful levels of detail here (as you created) but I don't love the names. Can we call them `device` and `device_category`?

2018-11-15 14:09 UTC, jthandy requested changes
@eogilvy12 I'm good to go on the overall business logic and agree that there are two useful levels of detail here (as you created) but I don't love the names. Can we call them `device` and `device_category`?

2019-01-24 14:55 UTC, eogilvy12 commented
@jthandy ready for final review!

2019-01-24 20:41 UTC, jthandy requested changes
This is very close. I just have a small code reorganization comment. Once that's done I'm good to merge.

2019-01-24 20:41 UTC, jthandy commented on macros/cross-adapter-modeling/sessionization/segment_web_page_views__sessionized.sql
> +        case
The whole point of this model (as it talks about in its docs and comments) is to create a session_id, and this logic isn't related to that. This should be in `snowplow_web_page_views`, right alongside the `device` field you just created.

2019-01-25 14:29 UTC, eogilvy12 commented on macros/cross-adapter-modeling/sessionization/segment_web_page_views__sessionized.sql
> +        case
@jthandy totally agree - updated!

2019-01-25 14:30 UTC, jthandy approved these changes

2019-01-25 15:41 UTC, merged